services:
  whatsapp:
    build: .
    container_name: whatsapp-server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - API_KEY=${API_KEY}
      - WHATSAPP_DATA_PATH=/app/whatsapp-session
      - CHROME_PATH=${CHROME_PATH:-/usr/bin/chromium-browser}
      - PUPPETEER_EXECUTABLE_PATH=${PUPPETEER_EXECUTABLE_PATH:-/usr/bin/chromium-browser}
    volumes:
      - whatsapp_session:/app/whatsapp-session
    shm_size: "1gb"
    restart: unless-stopped
volumes:
  whatsapp_session:
    driver: local
